import { db } from "../store/index.js";
import type { InvoiceRow, RestockOrderRow } from "../store/types.js";
import { invoiceValidatorAgent } from "./invoiceValidatorAgent.js";

/**
 * Supplier Invoice Agent: fires automatically the moment a human Supplier
 * approves a restock order (see routes/restock.ts's `:id/approve`). Bills
 * the Seller exactly the restock order's agreed total_cost — no manual
 * amount entry — and marks the restock order "invoiced". Immediately hands
 * the new invoice to the Invoice Validator Agent so the Seller sees a
 * pre-vetted invoice rather than a raw, unchecked one.
 */
export async function supplierInvoiceAgent(restockOrder: RestockOrderRow): Promise<InvoiceRow | null> {
  const invoice = await db.approveRestockOrder(
    restockOrder.id,
    restockOrder.total_cost,
    `Auto-generated by the Supplier Invoice Agent for vendor order ` +
      `${restockOrder.vendor_order_id ?? restockOrder.id} (${restockOrder.quantity}x ${restockOrder.sku}).`
  );
  if (!invoice) return null;

  if (restockOrder.order_id) {
    await db.logAgentStep(
      restockOrder.order_id,
      "supplier",
      "restock_goods_received",
      `Supplier approved and shipped ${restockOrder.quantity} unit(s) of ${restockOrder.sku} -- ` +
        `received into seller inventory atomically with invoice creation.`
    );
    await db.logAgentStep(
      restockOrder.order_id,
      "supplier_invoice",
      "invoice_sent",
      `Supplier Invoice Agent generated invoice ${invoice.id} for €${invoice.amount.toFixed(2)} and sent it to the Seller.`
    );
  }

  await invoiceValidatorAgent(invoice, restockOrder);

  return invoice;
}
